# when changing optimizer settings, make sure to also change settings in hardhat.config.ts
[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
optimizer = true
optimizer_runs = 20000
via_ir = false

compilation_restrictions = [
    { paths = "src/*", version = '0.8.16' },
    { paths = "test/*", version = '0.8.16' },
    { paths = "node_modules/@arbitrum/nitro-contracts/src/", version = '>=0.8.17', evm_version = 'cancun', optimizer_runs = 2000 },
]

[profile.sec_council_mgmt]
optimizer_runs = 750

[fmt]
number_underscore = 'thousands'
line_length = 100
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
