on: [push, pull_request]

name: test

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      
      - name: Install packages
        run: yarn

      - name: Run tests
        run: make test

      - name: Check gas snapshot
        run: make gas-check
