name: Yarn Audit
on: [pull_request]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Setup node/yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'
      
      - name: Install packages
        run: yarn

      - name: Install npm-audit-resolver
        run: npm i -g npm-audit-resolver

      - name: Run yarn audit
        run: check-audit --yarn

